### ISSUE TITLE
Request: Tutorial in game or on SMD/Github with visuals.

### ISSUE THREAD

**Issue by IR0NSIGHT** [taswin/LogicalGravityUnits#2]
Had a hard time figuring out the mechanics. Its intuitive once you know how it works, but impossible to figure out on your own.

**Comment by IR0NSIGHT** [comment]
![LGU Tutorial](https://user-images.githubusercontent.com/32139214/113426018-21d63100-93d3-11eb-87f9-30dfb515d407.png)

**Comment by taswin** [comment]
I copied your infographic over to the starmade-dock page.
Has this mod been broken by starmade updates?
